// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCurJ8lqwtiLTFsUgjCw9NYqa5e3t-bh00',
    appId: '1:362379143800:web:4c0cf256b40b181cae5b8d',
    messagingSenderId: '362379143800',
    projectId: 'hospital-management-214b8',
    authDomain: 'hospital-management-214b8.firebaseapp.com',
    storageBucket: 'hospital-management-214b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqneyNXf4WXfOSR0lhPzvaHzcfoC5eLuc',
    appId: '1:362379143800:android:3362df3fd8d7aa3aae5b8d',
    messagingSenderId: '362379143800',
    projectId: 'hospital-management-214b8',
    storageBucket: 'hospital-management-214b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVQwNtSgbYIO6yPSejZkzTerZJS9AcSo0',
    appId: '1:362379143800:ios:af056ddb27cb43e0ae5b8d',
    messagingSenderId: '362379143800',
    projectId: 'hospital-management-214b8',
    storageBucket: 'hospital-management-214b8.appspot.com',
    iosClientId: '362379143800-6kh0llkgqkotclj4qjrdp4nvildbdccs.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVQwNtSgbYIO6yPSejZkzTerZJS9AcSo0',
    appId: '1:362379143800:ios:5fa4389511ae7a87ae5b8d',
    messagingSenderId: '362379143800',
    projectId: 'hospital-management-214b8',
    storageBucket: 'hospital-management-214b8.appspot.com',
    iosClientId: '362379143800-hn079bphcul2o5hasu2hdjg3e60cut52.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalManagement.RunnerTests',
  );
}
